# Build script for Travis CI
#

# use xenial distribution
dist: xenial

# no need to check for oracle's java
language: java
jdk: openjdk8


# speed up builds by caching maven local repository
# we are also using python via conda/pip
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.cache/pip"
  - "$HOME/miniconda3"

# as agreed in our SOP
branches:
  only:
  - master
  - development
  # Travis treats pushed tags as branches
  - /^[vV]?\d+\.\d+\.\d+$/ # matches e.g., v1.2.3, 1.2.3, V1.2.3

# added to make logs look cleaner, crisper, certified fresh
before_install: unset _JAVA_OPTIONS 

# dependencies for report generation (use cache to speed up builds)
install: 
  - $HOME/miniconda3/bin/conda --version || ./.install-reports-dependencies.sh

# check if we need to add a license file for Vaadin charts
before_script: if [ "$VAADIN_CHARTS_LICENSE_CODE" != "" ]; then
                  echo "$VAADIN_CHARTS_LICENSE_CODE" > ~/.vaadin.charts.developer.license;
               fi;

# as agreed in our SOP, build everything (don't deploy, just try to 'mvn package' locally, which covers unit tests)
script: mvn --quiet --activate-profiles !development-build,!release-build --settings .travis.settings.xml clean cobertura:cobertura package
# upload code coverage report, generate maven site (javadocs, documentation, static code analysis, etc.)
after_success: 
- bash <(curl -s https://codecov.io/bash)

# upload to maven
deploy:
  # as agreed in our SOP, builds on development branch will deploy to our maven repository after validating
  # the artifact has a proper SNAPSHOT version
  # make sure to skip integration tests! (using -DskipITs)
- skip_cleanup: true
  provider: script
  script: mvn --quiet --activate-profiles development-build,!release-build --settings .travis.settings.xml deploy -DskipITs
  on:
    branch: development
    condition: '"$TRAVIS_EVENT_TYPE" = "push"'
  # as agreed in our SOP, releases are performed by tagging commits,
  # the version string and version of dependencies are validated (no snapshots allowed)
- skip_cleanup: true
  provider: script
  script: mvn --quiet --activate-profiles !development-build,release-build --settings .travis.settings.xml deploy -DskipITs
  on:
    condition: '"$TRAVIS_EVENT_TYPE" = "push"'
    tags: true

# activate our conda environment, generate maven site and upload reports to gh-pages branch
after_deploy:   
  - echo ". $HOME/miniconda3/etc/profile.d/conda.sh" >> ~/.bashrc && source ~/.bashrc && conda activate qbic-docs-build
  - mvn --quiet --activate-profiles !development-build,!release-build --settings .travis.settings.xml site 
  - ./.generate-reports.py $TRAVIS_BRANCH $TRAVIS_REPO_SLUG "[skip travis] Updated gh-pages" "This commit was performed from travis-ci.com using a personal access key" "Build ID $TRAVIS_BUILD_ID" "Job ID TRAVIS_JOB_ID" "Branch $TRAVIS_BRANCH" "Log of this build found at $TRAVIS_JOB_WEB_URL"

# credentials
env:
  global:
    - secure: "f0IFHFN5MgeQnnJEvh2WvGphQtmEYMX4fHb3Tzte9RU/909xN6MaAjo5D0ZZ2vCPlE9S18viytBwtCKWXi1ATID7rClHdveY8I+ZaAS9v3/7H44gzYc/SDVabOBBnW7gp63I0GWkrPIkGPuLva1fWLXfEeZY6QDi+CyA7jg8+UdtbseVNnzg0nM5g78HJ4bzeP/OMbnvnokl1yb++2OMl/htLLVH7JBv4EZxQOlVu+xyer9lagh9yLgd+gx4h4cNmDC9qrSxxBkhq0y4zf/ADliL2m0/M8Utrwg5xYumN69SP3TtcDiYXBTNc7ve/QwV9HGZdy8x9emwdfcVCLPTnGxJdCbuoPRJvvuhO+Nu97KOZs7inOuzPO393eSSqkePD983mPWoI4jv5j16SugVs48pQQ84XM3O0alwdHejOaIZy87Ru6hOER4y2QUyaaXGTYtd/O+aR3zgyDBipI1jVaI7kp826hH66IGN9ab4jOJr23qWi9IYQ+79epnIs6UIblHuhK83VN8Oc9yWZvDRfIizVlqAVdMMwHMVhIiRbNKImNF02k7LmiSAi2e4MuQI+slucpfHwzTcwKOlWaNW0cbh/Yhu4hhpXWitQtmz1921coWfOY85r4klfIV5Vkr90pvtXwKkMhyyTi+0tjvK9Ho2UZc5X5HDXPM+soGMvfI="
    - secure: "JUTqElHR66Cu/egFIWBq/IX9YPCR38JQZTtjVtu7QBN5GYhIGcNVB+zdOkW1/AxmOSU8lofpdiJBz6CAYmeUtYsKD2zOeUpTPLnCxT2snthyrqRS1bLUuANtlS9mo7b/9ul3i3S4/ohW4bC0QyvpzIdwQtwltnxft7C/3D2xADGMWfFWh38NVxYW1hSPNh2/VR0NvCFfwAeDgtiuWD3LZkVVCVG8N+9Z8H3Os21KLGJv4Azcfd0SF4lxQkMRVsbQSUiwzy5zas2KStYYGx2znqRaRQjxlE3w7hHyilWFzMaL2AafbnJKStuWIV4bkH2+/B0L+xMVggimMJjxhzWy0VMSpObFwVOGvW80NdApGaAvtvowmUhcETVs6cupZRLJPGr406SWCtFjnGobr9U8xe6d9dOS0S6zVaqkjVG3MGrRuVAlAUZcvkHLjc834DoqOWT5t+GJisf/auGwNAh0emH2q3vsLU1DrNERJsoj/kMmx/Nu53Gqns9BcQky6ORcQKzBkc1EsPQu1IQPnN2q8u5OLDAeyf/I55Ue3px/287to0otVwnnmOs8X73VqMUZByio5JRyNjlA4F3VsisOQYHf+GmgVapYCtP9qvrN4+tFNFqpqh7y8Q7uBg95nF8BAFsgNZJOtGIRa53PZi9xb7Rb4OQfIb+rV73LGR6Jrd0="
    - "hf0YxT4h55cdmnFyiHQims29knGnJQyO+/oNvzsTMGrawfyNofUrvFj+celxJvuqY/VyD6gcYI+C12Iz5HdQqLqiyvHObQQOjMNX+ggOycK+c70EMOv/i4MABDyjaC0eyqwFfKkBQSkTjrbUzIIzkgBUfilxTZ+/NBwQrpI+9C0zmaecP6kmlOXRTOIpeYT4gUXMtkPnCwyYODuktPDpRV9vwaTNjZMN0jVJfxIL084LLkc8w0F6Z9/qB6vGiuCXvCT93xJ0iNvxzDakXVSwSlBL4/C9m7nMsQECXwcInSsDUkL6ignJo/GDsqurzwjRLKPUI9aifsRg3bcHo7ZKqIc11SC4Q2j1iTbeY+T2KcyzO1HkYU+7SISXDSsfbTtTijK6QPKNpzJAH7aWr5jo3KKY391MfTT19MenHzCagDQAAkRDB7FJQn9Y5rqO0EQwrbK/q9VdudUbmdMENLGujqP+WUMQ5xtc9vDlC8DLPgWUbHV18W+H7r0M+DF+fHIx4vE9bi8sVD17rPsMfIwNaGVfWoLBeumtg4h4UEJwuXSg7YG0J5L8PrBTsWH8l9eAwt7dLH1wq9ahMKj7Wtd5YInqkhBDX6wh7fs4PxPcgSpIHLxWLde5oP2wXV9v1jgcFUmCbSDB5+toAs66tMeiO5yqS/puQGiI79ciBJdPKPo="
