language: java
jdk:
- openjdk8
sudo: false
cache:
  directories:
  - "$HOME/.m2/repository"
install: true
branches:
  only:
  - master
  - testing
script: "./.travis.sh"
after_success:
- bash <(curl -s https://codecov.io/bash)
- mvn --settings .travis.settings.xml site
notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    on_success: never
    on_failure: always
env:
  global:
  - secure: mGviSjWPVNnSZ7OXakNdny8jqIMGX3KGgvgogVUntjhi4tkTpA2Za+AWr7RtrlU0E/lDs5jd3TxMT4U5THK8F/TqPzunt2BxFLKhqT5iDKB6lkMz5ZFYx9ztGAEa0Ovr7O4ALotjpLMnJjguSbNy7XbGJQrfLdQz2nKGWma1OZMDLQ7QSFc1YofPh1YJGeMin1XvDMUM1lnR/txjyA3gL7FwnTMPk9mV/e79GvS4XAbMRygSvpxmpBlEre7mk3H7lkf2m32BeuFfXVjgkZAzhMurvMmP350TRWQ1yaZun/IvzF1wwpvjABBBbvJVR5/jNmMEwqGW0UaSeZ+k+GGWyikvmK2INWDXrRoCMlLkScotiSrEMGFlzFsocy3u7nec2+SXUr2cajCcmxr8dWMPbnBLWwdtB7DkG76vtW3NVcGqypT/VAKKA+HhbYTDlkBCCoIIIJi4/hYEBrXbVLF7TPLaXhoNH+kaPBgrhw66eVHLfPrxngBhYc82CD6HVSuzwWLicdHKpPaAwjagOvLlC60H8xjzuOWHUkFcD+DDWEjs6bdCkfeVTYd3aZRP8Sov55QbKq7PAS42ezXPtriogMs1ARFQUaRNFugCcTDT0aWih1+l474+jWjiczwweBKmynnB7lQA3eknq7vwFBoLWWwmJPgyNzJiMeThSJJY3jY=
  - secure: T7JxE1Fx/+WKsZKS7KEc2/4o4/CZ7djYOq55/r99QLI4NxXfFG9xf9lAOLZcj1kD1dkLTn9tEqTwcGvZuAEDgFWHtdjzU8HHzxk+Jq1eGxkafTFVOW72Vsa6y7GJkGCNszPphxcKCcseMW9lvTb+e+UySTQ6FuHp3QwJMJYaBvol/lONFPOIgjpmKaJDqP9hSAfGHPcHqfagvycwleOOqgy1Jh3CX9wVOCi7sH9Uv9AJJDjeE3V+8xXBRTjmLFmlK9nbnKKv4tWkFWUpmCtq9aEseEYxxVcZVt3D1kbH6+vBpi8PyQXwg34HQoA6nzVFaDtM189PzPuBa+CF+BEXiIikrYEqFKjRJgFDnKYsNA14tdtJKxgCplwO+u2un2FFvZEinMfM3GI/AtCqaxARZoDBZmbSzIlV8kOYkOXO/Pt7VyhtSyo90dH7RGTH6vgY3LnI7q72gGCwiR2KJ8O2VlpYQ+/+lj5NrvpHkO216rk0OMJ8gOdLdV15Cbf7Ljy5xmUDLG+PXdgFNAF6T8pVVKtLPE/fIgFoPNVDuMOGtWSB8gsWbziz/YEammkgg8Tv3V89ciida3UIHT0ytTXuY644UYgrCo660Yv9KG/hwLE7RaB20S/WDUVe/QYhr+ac7Qs2jBQRDeQDjQAk95384dj5FKNG+jnm3rlAaZ3OJzs=
